### ISSUE TITLE
Local name of a language

### ISSUE THREAD

**Issue by xErik** [TiagoDanin/Locale-Codes#1]
Thanks for providing this module.

Do you plan to add the local name of the language?

I found this package which includes them but lacks sub-languages (macro-language pattern) you include:

`https://github.com/adlawson/nodejs-langs/blob/master/data.js`

Examples:
Local name for `German` would be `Deutsch`.
Local name for `Greek` would be `Ελληνικά`.

**Comment by TiagoDanin** [comment]
Nice! Next version I'll add this...

**Comment by TiagoDanin** [comment]
Done! Added in version 1.1.0
https://github.com/TiagoDanin/Locale-Codes/releases/tag/v1.1.0
